In [1]:
import pandas as pd
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
import string
from nltk import word_tokenize

/opt/anaconda3/lib/python3.12/site-packages/pandas/core/computation/expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.7' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/opt/anaconda3/lib/python3.12/site-packages/pandas/core/arrays/masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (

In [3]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential,load_model
from tensorflow.keras.layers import Embedding, Dense,Input,GlobalAveragePooling1D,Flatten,LSTM
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [41]:
from keras.utils import to_categorical

In [5]:
df = pd.read_csv("./data/text/synthetic_binary_sentiment_dataset_clean.csv")

In [7]:
df.head()

                                     sentence   emotion
0  I am impressed by how good this turned out  positive
1  I am impressed by how good this turned out  positive
2      I love this product it works perfectly  positive
3      Nothing went right horrible experience  negative
4      Nothing went right horrible experience  negative

In [13]:
df_train = pd.read_csv("./data/Covid/Corona_NLP_train.csv",encoding='latin-1')

In [15]:
df_train.head()

,UserName,ScreenName,Location,TweetAt,OriginalTweet,Sentiment
0,3799,48751,London,16-03-2020,@MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...,Neutral
1,3800,48752,UK,16-03-2020,advice Talk to your neighbours family to excha...,Positive
2,3801,48753,Vagabonds,16-03-2020,Coronavirus Australia: Woolworths to give elde...,Positive
3,3802,48754,NaN,16-03-2020,My food stock is not the only one which is emp...,Positive
4,3803,48755,NaN,16-03-2020,"Me, ready to go at supermarket during the #COV...",Extremely Negative

In [17]:
df_train["Sentiment"].value_counts()

Sentiment
Positive              11422
Negative               9917
Neutral                7713
Extremely Positive     6624
Extremely Negative     5481
Name: count, dtype: int64

In [19]:
wl = WordNetLemmatizer()
stp_wrds = stopwords.words("english")
translator = str.maketrans('','',string.punctuation)

In [21]:
def clean_text(text):
    word_tok = word_tokenize(text)
    lemma_word = [wl.lemmatize(word,pos='v') for word in word_tok if word.lower() not in stp_wrds]
    lowercase_lemma_word = [word.lower() for word in lemma_word]
    processed_text = " ".join(lowercase_lemma_word).translate(translator).strip()
    return processed_text

In [23]:
text = "Hello, World! Python is amazing."
clean_text(text)

'hello  world  python amaze'

In [25]:
df_train["Cleaned_tweet"] = df_train["OriginalTweet"].apply(lambda x:clean_text(x))

In [27]:
df_train.head()

,UserName,ScreenName,Location,TweetAt,OriginalTweet,Sentiment,Cleaned_tweet
0,3799,48751,London,16-03-2020,@MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...,Neutral,menyrbie philgahan chrisitv https tcoifz9fa...
1,3800,48752,UK,16-03-2020,advice Talk to your neighbours family to excha...,Positive,advice talk neighbour family exchange phone nu...
2,3801,48753,Vagabonds,16-03-2020,Coronavirus Australia: Woolworths to give elde...,Positive,coronavirus australia woolworths give elderly...
3,3802,48754,NaN,16-03-2020,My food stock is not the only one which is emp...,Positive,food stock one empty please nt panic enough...
4,3803,48755,NaN,16-03-2020,"Me, ready to go at supermarket during the #COV...",Extremely Negative,ready go supermarket covid19 outbreak m para...

In [43]:
X = df_train["Cleaned_tweet"].values
y = df_train["Sentiment"].values

In [33]:
X[0]

'menyrbie  philgahan  chrisitv https  tcoifz9fan2pa https  tcoxx6ghgfzcc https  tcoi2nlzdxno8'

In [35]:
X.shape

(41157,)

In [49]:
le = LabelEncoder()
y = le.fit_transform(y)

In [51]:
y

array([3, 4, 4, ..., 4, 3, 2])

In [53]:
y_train = to_categorical(y, num_classes=5)

In [55]:
y_train

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       ...,
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.]])

In [67]:
# tokenizer = Tokenizer(num_words=10,oov_token="<OOV>")

In [143]:
tokenizer = Tokenizer(num_words=1000)

In [145]:
tokenizer.fit_on_texts(X)

In [147]:
word_index = tokenizer.word_index

In [149]:
X[0]

'menyrbie  philgahan  chrisitv https  tcoifz9fan2pa https  tcoxx6ghgfzcc https  tcoi2nlzdxno8'

In [151]:
word_index

{'https': 1,
 'coronavirus': 2,
 'covid19': 3,
 'price': 4,
 'store': 5,
 'food': 6,
 'supermarket': 7,
 'grocery': 8,
 'people': 9,
 'amp': 10,
 'go': 11,
 'shop': 12,
 '19': 13,
 'consumer': 14,
 'get': 15,
 'covid': 16,
 'need': 17,
 's': 18,
 'online': 19,
 'buy': 20,
 'pandemic': 21,
 'time': 22,
 'work': 23,
 'hand': 24,
 'us': 25,
 'workers': 26,
 'help': 27,
 'stock': 28,
 'panic': 29,
 'make': 30,
 'nt': 31,
 'like': 32,
 'home': 33,
 'sanitizer': 34,
 'demand': 35,
 'say': 36,
 'take': 37,
 'see': 38,
 'supply': 39,
 'one': 40,
 'due': 41,
 'keep': 42,
 'mask': 43,
 'oil': 44,
 'new': 45,
 'please': 46,
 'stay': 47,
 'covid2019': 48,
 'use': 49,
 'crisis': 50,
 'toiletpaper': 51,
 'market': 52,
 'toilet': 53,
 'retail': 54,
 'think': 55,
 'paper': 56,
 'local': 57,
 'know': 58,
 'today': 59,
 'via': 60,
 'many': 61,
 'still': 62,
 'increase': 63,
 'shelve': 64,
 'delivery': 65,
 'stop': 66,
 '2': 67,
 'come': 68,
 'spread': 69,
 'impact': 70,
 'close': 71,
 'would': 72,
 'lockdown': 73,
 'look': 74,
 'find': 75,
 'staff': 76,
 'thank': 77,
 'day': 78,
 'outbreak': 79,
 'could': 80,
 'virus': 81,
 'even': 82,
 'service': 83,
 'health': 84,
 'everyone': 85,
 'social': 86,
 'order': 87,
 'change': 88,
 'also': 89,
 'face': 90,
 'business': 91,
 'want': 92,
 'give': 93,
 'right': 94,
 'company': 95,
 'distance': 96,
 'world': 97,
 'week': 98,
 'amid': 99,
 'good': 100,
 'socialdistancing': 101,
 'essential': 102,
 'pay': 103,
 '1': 104,
 'live': 105,
 'safe': 106,
 'customers': 107,
 'line': 108,
 'open': 109,
 'support': 110,
 'way': 111,
 'report': 112,
 'put': 113,
 'employees': 114,
 'back': 115,
 'products': 116,
 'test': 117,
 'call': 118,
 'sell': 119,
 'government': 120,
 'every': 121,
 'may': 122,
 'leave': 123,
 'much': 124,
 'first': 125,
 'items': 126,
 'try': 127,
 'last': 128,
 'quarantine': 129,
 'chain': 130,
 'risk': 131,
 'read': 132,
 'news': 133,
 '3': 134,
 'bank': 135,
 're': 136,
 'coronacrisis': 137,
 'tell': 138,
 'free': 139,
 'start': 140,
 'run': 141,
 'corona': 142,
 'low': 143,
 'empty': 144,
 'job': 145,
 'itâ\x92s': 146,
 'around': 147,
 'continue': 148,
 'days': 149,
 'global': 150,
 'check': 151,
 'supermarkets': 152,
 'well': 153,
 'economy': 154,
 'weeks': 155,
 'uk': 156,
 'gas': 157,
 'fight': 158,
 'high': 159,
 'donâ\x92t': 160,
 'public': 161,
 'care': 162,
 'm': 163,
 'offer': 164,
 'money': 165,
 'state': 166,
 'house': 167,
 'really': 168,
 'since': 169,
 'share': 170,
 'let': 171,
 'businesses': 172,
 'consumers': 173,
 'ask': 174,
 'wear': 175,
 'place': 176,
 'prices': 177,
 'iâ\x92m': 178,
 'country': 179,
 'protect': 180,
 'drop': 181,
 'provide': 182,
 'cause': 183,
 'show': 184,
 'next': 185,
 'great': 186,
 'things': 187,
 'case': 188,
 'enough': 189,
 'two': 190,
 'others': 191,
 'long': 192,
 '2020': 193,
 'available': 194,
 'hoard': 195,
 'spend': 196,
 'march': 197,
 'full': 198,
 'fall': 199,
 'limit': 200,
 'hours': 201,
 'gloves': 202,
 'family': 203,
 'update': 204,
 'roll': 205,
 'die': 206,
 'post': 207,
 'rise': 208,
 'anyone': 209,
 'feel': 210,
 '4': 211,
 'lot': 212,
 'across': 213,
 'response': 214,
 'medical': 215,
 'include': 216,
 'follow': 217,
 'amazon': 218,
 'industry': 219,
 'must': 220,
 'scam': 221,
 'china': 222,
 'trump': 223,
 'mean': 224,
 'reduce': 225,
 'life': 226,
 'drive': 227,
 'learn': 228,
 've': 229,
 'everything': 230,
 'ca': 231,
 'hit': 232,
 'groceries': 233,
 'goods': 234,
 'without': 235,
 'allow': 236,
 'list': 237,
 'affect': 238,
 'end': 239,
 'big': 240,
 'emergency': 241,
 'wash': 242,
 'economic': 243,
 'best': 244,
 'etc': 245,
 'cut': 246,
 '10': 247,
 'already': 248,
 'never': 249,
 'sure': 250,
 'meet': 251,
 'thing': 252,
 'community': 253,
 'plan': 254,
 'vulnerable': 255,
 'deliver': 256,
 'avoid': 257,
 'visit': 258,
 'drivers': 259,
 'stayhome': 260,
 '5': 261,
 'per': 262,
 'elderly': 263,
 'small': 264,
 'sales': 265,
 'wait': 266,
 'happen': 267,
 'purchase': 268,
 'fear': 269,
 'someone': 270,
 'coronavirusoutbreak': 271,
 'coronaviruspandemic': 272,
 'issue': 273,
 'better': 274,
 'situation': 275,
 'healthcare': 276,
 'part': 277,
 'clean': 278,
 'latest': 279,
 'behavior': 280,
 'shoppers': 281,
 'deal': 282,
 'year': 283,
 'bring': 284,
 'queue': 285,
 'another': 286,
 'real': 287,
 'donate': 288,
 'panicbuying': 289,
 'measure': 290,
 'hope': 291,
 'canâ\x92t': 292,
 'hard': 293,
 'gt': 294,
 'away': 295,
 'nurse': 296,
 'data': 297,
 'expect': 298,
 'eat': 299,
 'water': 300,
 'important': 301,
 'stayathome': 302,
 'produce': 303,
 'morning': 304,
 'together': 305,
 'retailers': 306,
 'able': 307,
 'production': 308,
 'watch': 309,
 'shift': 310,
 'person': 311,
 'information': 312,
 'force': 313,
 'daily': 314,
 'protection': 315,
 'number': 316,
 'tesco': 317,
 'nhs': 318,
 'result': 319,
 'raise': 320,
 'lose': 321,
 'lower': 322,
 'tip': 323,
 'front': 324,
 'current': 325,
 'save': 326,
 'talk': 327,
 'send': 328,
 'might': 329,
 'cost': 330,
 'become': 331,
 'positive': 332,
 '20': 333,
 'walk': 334,
 'hike': 335,
 'travel': 336,
 'love': 337,
 'key': 338,
 'financial': 339,
 'else': 340,
 'contact': 341,
 'normal': 342,
 'remain': 343,
 'essentials': 344,
 'less': 345,
 'concern': 346,
 'ever': 347,
 'stayhomesavelives': 348,
 'cough': 349,
 'remember': 350,
 'u': 351,
 'outside': 352,
 'worry': 353,
 'create': 354,
 'safety': 355,
 'least': 356,
 'fuck': 357,
 'surge': 358,
 'brand': 359,
 'doctor': 360,
 'begin': 361,
 'police': 362,
 'milk': 363,
 'step': 364,
 'soap': 365,
 'consider': 366,
 'join': 367,
 'nothing': 368,
 'little': 369,
 'lead': 370,
 'man': 371,
 'do': 372,
 'set': 373,
 '6': 374,
 'shortage': 375,
 'self': 376,
 'hear': 377,
 'announce': 378,
 'trip': 379,
 'years': 380,
 'experience': 381,
 'wipe': 382,
 'effect': 383,
 'restaurants': 384,
 'months': 385,
 'something': 386,
 'yet': 387,
 'prevent': 388,
 'access': 389,
 'question': 390,
 'india': 391,
 'video': 392,
 'sign': 393,
 'group': 394,
 'shopping': 395,
 'stophoarding': 396,
 'point': 397,
 'sick': 398,
 'families': 399,
 'move': 400,
 'struggle': 401,
 'farmers': 402,
 'april': 403,
 'charge': 404,
 'shut': 405,
 'worker': 406,
 'relate': 407,
 'ecommerce': 408,
 'trade': 409,
 'understand': 410,
 'kill': 411,
 'stockpile': 412,
 'possible': 413,
 'americans': 414,
 'drug': 415,
 'ensure': 416,
 'control': 417,
 'month': 418,
 'higher': 419,
 'always': 420,
 'coronavirusupdate': 421,
 'media': 422,
 'turn': 423,
 'bad': 424,
 'bottle': 425,
 'instead': 426,
 'likely': 427,
 'tp': 428,
 'old': 429,
 'govt': 430,
 'challenge': 431,
 'covid19uk': 432,
 'll': 433,
 'warn': 434,
 'sanitizers': 435,
 'pack': 436,
 'soon': 437,
 'major': 438,
 'school': 439,
 'alcohol': 440,
 'email': 441,
 'act': 442,
 'city': 443,
 'isolation': 444,
 '100': 445,
 'hold': 446,
 'shortages': 447,
 'pick': 448,
 'stand': 449,
 'hospital': 450,
 'advice': 451,
 'relief': 452,
 'touch': 453,
 '50': 454,
 'anything': 455,
 'walmart': 456,
 'package': 457,
 'kid': 458,
 'prepare': 459,
 'grow': 460,
 'pharmacy': 461,
 'healthy': 462,
 'advantage': 463,
 'yesterday': 464,
 'na': 465,
 'guy': 466,
 'especially': 467,
 'bag': 468,
 'link': 469,
 'friends': 470,
 'selfish': 471,
 'far': 472,
 'practice': 473,
 'trend': 474,
 'article': 475,
 'stuff': 476,
 'special': 477,
 'almost': 478,
 'level': 479,
 'top': 480,
 'team': 481,
 'thanks': 482,
 'profit': 483,
 'w': 484,
 'action': 485,
 'website': 486,
 'staysafe': 487,
 'break': 488,
 'car': 489,
 'whole': 490,
 'realdonaldtrump': 491,
 'saw': 492,
 'system': 493,
 'war': 494,
 'interest': 495,
 'meat': 496,
 'add': 497,
 'fuel': 498,
 'â\x97': 499,
 'stoppanicbuying': 500,
 'customer': 501,
 'slot': 502,
 'credit': 503,
 '30': 504,
 'million': 505,
 'youâ\x92re': 506,
 'info': 507,
 'survive': 508,
 'cash': 509,
 'fresh': 510,
 'catch': 511,
 'actually': 512,
 'egg': 513,
 'story': 514,
 'bread': 515,
 'receive': 516,
 'seem': 517,
 'heroes': 518,
 'despite': 519,
 'gouge': 520,
 'inflate': 521,
 '12': 522,
 'benefit': 523,
 'bill': 524,
 'shit': 525,
 'base': 526,
 'russia': 527,
 'closure': 528,
 'head': 529,
 'huge': 530,
 'countries': 531,
 'area': 532,
 'extra': 533,
 '7': 534,
 'quarantinelife': 535,
 'â\x96': 536,
 'hour': 537,
 'kind': 538,
 'maybe': 539,
 'clear': 540,
 'canada': 541,
 'period': 542,
 'message': 543,
 'handsanitizer': 544,
 'iâ\x92ve': 545,
 'fund': 546,
 'crowd': 547,
 'rule': 548,
 'woman': 549,
 '15': 550,
 'moment': 551,
 'collapse': 552,
 'early': 553,
 'product': 554,
 'fee': 555,
 'critical': 556,
 'idea': 557,
 'restaurant': 558,
 'security': 559,
 'america': 560,
 'difficult': 561,
 'reason': 562,
 'isolate': 563,
 'personal': 564,
 'yes': 565,
 'weâ\x92re': 566,
 'ago': 567,
 'park': 568,
 'three': 569,
 'employee': 570,
 'national': 571,
 'pass': 572,
 'different': 573,
 'gold': 574,
 'basic': 575,
 'scammers': 576,
 'â\x95': 577,
 'ways': 578,
 'italy': 579,
 'currently': 580,
 'believe': 581,
 'cashier': 582,
 'notice': 583,
 'cover': 584,
 'research': 585,
 'play': 586,
 'wonder': 587,
 'enter': 588,
 'seriously': 589,
 'truck': 590,
 '8': 591,
 'energy': 592,
 'sainsburys': 593,
 'inside': 594,
 'manage': 595,
 'sector': 596,
 'experts': 597,
 'crazy': 598,
 'president': 599,
 'behaviour': 600,
 'forget': 601,
 'book': 602,
 'restrictions': 603,
 'amount': 604,
 'asda': 605,
 'tomorrow': 606,
 'answer': 607,
 'decline': 608,
 'bite': 609,
 'deliveries': 610,
 'card': 611,
 'claim': 612,
 'alert': 613,
 'nation': 614,
 'ppl': 615,
 'cancel': 616,
 'future': 617,
 'â': 618,
 'large': 619,
 'reach': 620,
 'recent': 621,
 'fill': 622,
 'survey': 623,
 'return': 624,
 'wrong': 625,
 'confidence': 626,
 'ppe': 627,
 'fast': 628,
 'focus': 629,
 'recession': 630,
 'listen': 631,
 'hey': 632,
 'american': 633,
 'infect': 634,
 'plenty': 635,
 'gon': 636,
 'near': 637,
 'folks': 638,
 'london': 639,
 'usa': 640,
 'office': 641,
 'slow': 642,
 'crude': 643,
 'short': 644,
 'term': 645,
 'sit': 646,
 'ready': 647,
 'cure': 648,
 'borisjohnson': 649,
 'record': 650,
 'fruit': 651,
 'pasta': 652,
 'write': 653,
 'phone': 654,
 'ones': 655,
 'light': 656,
 'problem': 657,
 'discuss': 658,
 'clerk': 659,
 'ship': 660,
 'couple': 661,
 'frontline': 662,
 'past': 663,
 'worse': 664,
 'strong': 665,
 'station': 666,
 'double': 667,
 'urge': 668,
 'household': 669,
 'wo': 670,
 'handle': 671,
 'agree': 672,
 'australia': 673,
 'â\x94': 674,
 'chinese': 675,
 'afford': 676,
 'resources': 677,
 'respond': 678,
 'insights': 679,
 'serve': 680,
 'pm': 681,
 'launch': 682,
 'longer': 683,
 'though': 684,
 'probably': 685,
 'general': 686,
 'habit': 687,
 'behind': 688,
 'hire': 689,
 'buyers': 690,
 'expose': 691,
 'digital': 692,
 'waste': 693,
 'equipment': 694,
 'treat': 695,
 'note': 696,
 'coronavirusuk': 697,
 'box': 698,
 'god': 699,
 'citizens': 700,
 'parent': 701,
 'ceo': 702,
 'appreciate': 703,
 'speak': 704,
 'explain': 705,
 'rice': 706,
 'poor': 707,
 'blog': 708,
 'single': 709,
 '60': 710,
 'federal': 711,
 'happy': 712,
 'wake': 713,
 'night': 714,
 'sale': 715,
 'law': 716,
 'monday': 717,
 'foods': 718,
 'second': 719,
 'hospitals': 720,
 'maintain': 721,
 'necessary': 722,
 'friend': 723,
 'members': 724,
 'half': 725,
 'efforts': 726,
 'rent': 727,
 'toiletpapercrisis': 728,
 'ration': 729,
 'nice': 730,
 'rs': 731,
 'ok': 732,
 'medicine': 733,
 'side': 734,
 'n': 735,
 'door': 736,
 '000': 737,
 'volunteer': 738,
 'serious': 739,
 'potential': 740,
 'game': 741,
 'contract': 742,
 'insurance': 743,
 'symptoms': 744,
 'push': 745,
 'county': 746,
 'thereâ\x92s': 747,
 'guess': 748,
 'society': 749,
 'toiletpaperpanic': 750,
 'direct': 751,
 'click': 752,
 'require': 753,
 'seniors': 754,
 'kit': 755,
 'power': 756,
 '25': 757,
 'value': 758,
 'unprecedented': 759,
 'crash': 760,
 'saudi': 761,
 'regard': 762,
 'human': 763,
 'california': 764,
 'however': 765,
 'worth': 766,
 'finally': 767,
 'date': 768,
 'build': 769,
 'morrisons': 770,
 'lock': 771,
 'easter': 772,
 'massive': 773,
 'hygiene': 774,
 'sanitize': 775,
 'anxiety': 776,
 'income': 777,
 'tax': 778,
 'apart': 779,
 'target': 780,
 'south': 781,
 'responders': 782,
 'chance': 783,
 'disease': 784,
 'mind': 785,
 'carry': 786,
 'ftc': 787,
 'decide': 788,
 'usual': 789,
 'ban': 790,
 'death': 791,
 'residents': 792,
 'distribution': 793,
 'confirm': 794,
 'freeze': 795,
 'stress': 796,
 'age': 797,
 'shock': 798,
 'true': 799,
 'rather': 800,
 'profiteer': 801,
 'd': 802,
 'pressure': 803,
 'biggest': 804,
 'temporarily': 805,
 'mass': 806,
 'donations': 807,
 'communities': 808,
 'street': 809,
 'sentiment': 810,
 'several': 811,
 'thatâ\x92s': 812,
 'hoarders': 813,
 'cart': 814,
 'space': 815,
 'baby': 816,
 'farm': 817,
 'pretty': 818,
 'deserve': 819,
 'went': 820,
 'dear': 821,
 'policy': 822,
 '9': 823,
 'till': 824,
 'miss': 825,
 'warehouse': 826,
 'calm': 827,
 'easy': 828,
 'debt': 829,
 'rate': 830,
 'unemployment': 831,
 'dont': 832,
 'fake': 833,
 'commodities': 834,
 'among': 835,
 'cheap': 836,
 'respect': 837,
 'minister': 838,
 'rt': 839,
 'plummet': 840,
 'account': 841,
 'imagine': 842,
 'gov': 843,
 'growth': 844,
 'bc': 845,
 'condition': 846,
 'theyâ\x92re': 847,
 'shame': 848,
 '14': 849,
 'opec': 850,
 'restock': 851,
 'firm': 852,
 'webinar': 853,
 'process': 854,
 'release': 855,
 'children': 856,
 'going': 857,
 'partner': 858,
 'ebay': 859,
 'track': 860,
 'word': 861,
 'finance': 862,
 'hi': 863,
 'plunge': 864,
 'suffer': 865,
 'department': 866,
 'skyrocket': 867,
 'vegetables': 868,
 'source': 869,
 'manufacture': 870,
 'wish': 871,
 'protective': 872,
 'dr': 873,
 'loan': 874,
 'picture': 875,
 'later': 876,
 'boost': 877,
 'giant': 878,
 'oh': 879,
 'spike': 880,
 'accord': 881,
 'study': 882,
 'priority': 883,
 'meals': 884,
 'quick': 885,
 'sir': 886,
 'cook': 887,
 'simple': 888,
 'quickly': 889,
 'delay': 890,
 'shelf': 891,
 'encourage': 892,
 'fail': 893,
 'wine': 894,
 'thousands': 895,
 'weekly': 896,
 'fix': 897,
 'matter': 898,
 'deaths': 899,
 'request': 900,
 'detail': 901,
 'app': 902,
 'rest': 903,
 'drink': 904,
 'youtube': 905,
 'along': 906,
 'tonight': 907,
 'coronavirususa': 908,
 'stimulus': 909,
 'certain': 910,
 'producers': 911,
 'weekend': 912,
 'panicbuyinguk': 913,
 'discount': 914,
 'aisle': 915,
 'plus': 916,
 'sense': 917,
 'fraud': 918,
 'commission': 919,
 'ahead': 920,
 'four': 921,
 'letâ\x92s': 922,
 'fact': 923,
 'lack': 924,
 'within': 925,
 'areas': 926,
 'address': 927,
 'millions': 928,
 'checkout': 929,
 'absolutely': 930,
 'non': 931,
 'property': 932,
 'whether': 933,
 'eye': 934,
 'either': 935,
 'aisles': 936,
 'r': 937,
 'bare': 938,
 '40': 939,
 'petrol': 940,
 'regular': 941,
 'worst': 942,
 'doesnâ\x92t': 943,
 'ridiculous': 944,
 'europe': 945,
 'bulk': 946,
 'name': 947,
 'piece': 948,
 'stick': 949,
 'patients': 950,
 'view': 951,
 'soar': 952,
 'total': 953,
 'amidst': 954,
 '24': 955,
 'gift': 956,
 'class': 957,
 'center': 958,
 'suggest': 959,
 'apply': 960,
 'b': 961,
 'coronaviruslockdown': 962,
 'lol': 963,
 'older': 964,
 'often': 965,
 'feed': 966,
 'isnâ\x92t': 967,
 'pickup': 968,
 'flight': 969,
 'buying': 970,
 'internet': 971,
 'rat': 972,
 'tweet': 973,
 'opportunity': 974,
 'develop': 975,
 'register': 976,
 'tech': 977,
 'slash': 978,
 'transport': 979,
 'operations': 980,
 'epidemic': 981,
 'amaze': 982,
 'combat': 983,
 'town': 984,
 'facebook': 985,
 'suppose': 986,
 'air': 987,
 'options': 988,
 'pharmacies': 989,
 'hoarding': 990,
 'thursday': 991,
 'pet': 992,
 'funny': 993,
 'n95': 994,
 'clothe': 995,
 'bus': 996,
 'lady': 997,
 'temporary': 998,
 'waitrose': 999,
 'busy': 1000,
 ...}

In [153]:
sequences = tokenizer.texts_to_sequences(X)

In [155]:
sequences

[[1, 1, 1],
 [451,
  327,
  203,
  654,
  316,
  354,
  341,
  237,
  654,
  316,
  439,
  373,
  19,
  12,
  841,
  39,
  941,
  87],
 [2, 673, 93, 263, 12, 201, 99, 3, 79, 1],
 [6,
  28,
  40,
  144,
  46,
  31,
  29,
  189,
  6,
  85,
  37,
  17,
  47,
  827,
  47,
  106,
  3,
  3,
  2,
  1],
 [647,
  11,
  7,
  3,
  79,
  163,
  6,
  28,
  144,
  2,
  739,
  252,
  46,
  31,
  29,
  183,
  375,
  302,
  1],
 [133,
  125,
  794,
  3,
  188,
  68,
  746,
  128,
  98,
  9,
  532,
  5,
  268,
  278,
  39,
  24,
  34,
  6,
  53,
  56,
  234,
  112,
  1],
 [582, 8, 5, 170, 679, 3, 163, 957, 58, 163, 327, 1],
 [7, 59, 31, 20, 53, 56, 728, 3, 1],
 [41,
  3,
  54,
  5,
  109,
  91,
  957,
  185,
  190,
  155,
  361,
  717,
  197,
  148,
  854,
  19,
  654,
  87,
  342,
  77,
  410,
  1],
 [142,
  66,
  20,
  187,
  509,
  49,
  19,
  142,
  69,
  696,
  89,
  19,
  12,
  33,
  18,
  22,
  158,
  16,
  13],
 [418, 31, 547, 152, 384, 765, 225, 201, 71, 224, 85, 49, 709, 7, 73, 48, 1],
 [41, 3, 275, 63, 35, 6, 116, 266, 22, 122, 683, 19, 87, 170, 436, 77, 22],
 [162, 253, 922, 74, 345, 416, 47, 462, 12, 27, 19, 12, 376, 444, 744, 691, 1],
 [31, 17, 28, 6, 433, 218, 256, 17, 2, 218, 1],
 [3, 958, 336, 679, 27, 336, 47, 14, 336, 280, 1, 1],
 [8, 5, 299, 106, 75, 933, 257, 384, 94, 1, 2, 3, 1],
 [1],
 [527, 14, 112, 188, 159, 371, 336, 3, 1, 1],
 [218,
  490,
  718,
  510,
  8,
  610,
  3,
  69,
  38,
  63,
  9,
  12,
  19,
  233,
  674,
  36,
  319,
  70,
  238,
  1],
 [31, 401, 46, 366, 288, 6, 135, 35, 83, 63, 3, 70, 145, 9, 18, 111, 226],
 [445,
  16,
  13,
  97,
  220,
  586,
  222,
  445,
  220,
  35,
  222,
  45,
  108,
  6,
  675,
  226,
  150],
 [1, 3, 2, 21, 70, 14, 12, 280, 268, 54, 265, 881, 125, 882],
 [836, 48, 11, 27, 177, 25, 83, 836],
 [836, 48, 11, 27, 177, 25, 83, 836],
 [372, 416, 6, 102, 116, 152, 29, 20, 123, 929, 76, 362, 485, 471, 801],
 [156,
  14,
  298,
  3,
  18,
  70,
  128,
  385,
  522,
  197,
  298,
  63,
  185,
  38,
  198,
  319,
  2,
  14,
  626,
  1,
  1],
 [419, 35, 740, 6, 375, 268, 247, 6, 45, 41, 3, 2, 1],
 [304,
  117,
  332,
  16,
  13,
  210,
  732,
  744,
  472,
  563,
  169,
  75,
  413,
  81,
  47,
  33,
  9,
  42,
  204,
  178,
  29,
  1],
 [38, 4, 63, 866, 14, 406, 315, 373, 752, 1, 49, 861, 1, 3],
 [437, 39, 9, 488, 10, 152, 50, 773, 2, 10],
 [179, 144, 64, 9, 38, 20, 6, 28],
 [718, 8, 5, 40, 1, 2, 271, 3, 16, 13, 3, 48, 552],
 [54, 5, 528, 80, 2, 60, 1, 1],
 [2, 923, 349, 8, 5, 15, 490, 915, 818, 889, 271, 2, 48],
 [136, 36, 616, 41, 3, 84, 76, 480, 883, 122, 183, 607, 469, 1],
 [820, 7, 464, 53, 56, 11, 455, 142, 81, 48],
 [565,
  20,
  17,
  18,
  397,
  207,
  9,
  7,
  476,
  80,
  20,
  263,
  701,
  458,
  245,
  231,
  31,
  20,
  230,
  17,
  3],
 [70, 325, 3, 21, 862, 323, 27, 595, 165, 431, 22, 3, 1, 1],
 [23,
  54,
  10,
  501,
  68,
  464,
  349,
  36,
  3,
  900,
  278,
  5,
  95,
  41,
  330,
  481,
  10,
  278,
  136,
  636,
  465,
  398,
  41],
 [11, 7, 32, 235, 271, 48, 1],
 [136, 182, 106, 12, 381, 107, 462, 253, 19, 87, 176, 1, 2, 271, 3, 1],
 [55, 54, 281, 212, 19, 12, 845, 136, 33, 11, 55, 85, 15, 533, 154, 2, 3, 260],
 [151, 392, 1, 6, 640, 52, 41, 2, 29, 636, 465, 206, 271, 2, 3, 21, 456, 1],
 [514, 19, 995, 12, 208, 9, 75, 995, 535, 271, 2, 1],
 [108, 352, 780, 107, 266, 5, 109, 304],
 [781, 28, 6, 575, 234, 2, 29, 232, 1, 3, 1],
 [46,
  170,
  58,
  270,
  401,
  15,
  67,
  57,
  7,
  41,
  273,
  147,
  13,
  164,
  139,
  610,
  462,
  209,
  17,
  916],
 [9, 207, 170, 725, 144, 64, 118, 9, 12, 8, 5, 963, 2, 3],
 [249, 55, 802, 36, 68, 115, 46, 2, 3, 500],
 [3, 603, 141, 5, 136, 71, 387, 107, 28, 912, 459, 80, 54, 5, 603, 68, 149, 1],
 [230, 566, 38, 325, 3, 79, 38, 208, 269, 29, 20, 6, 733, 648, 1],
 [85, 71, 343, 109, 241, 5, 77, 54, 26, 3, 21, 101, 54, 1],
 [28,
  300,
  183,
  95,
  405,
  21,
  439,
  71,
  321,
  23,
  183,
  458,
  11,
  292,
  676,
  385,
  766,
  6,
  2,
  1],
 [821,
  2,
  229,
  217,
  86,
  96,
  548,
  47,
  33,
  388,
  69,
  765,
  229,
  196,
  604,
  165,
  12,
  19,
  171,
  58,
  2],
 [150,
  6,
  4,
  69,
  16,
  13,
  213,
  811,
  80,
  38,
  803,
  68,
  385,
  41,
  148,
  153,
  39,
  52,
  70,
  35,
  319,
  81],
 [304, 85, 186, 106, 78, 2, 500],
 [187,
  29,
  20,
  241,
  31,
  15,
  53,
  56,
  301,
  136,
  942,
  188,
  242,
  49,
  165,
  6,
  598,
  2],
 [77,
  8,
  659,
  820,
  8,
  5,
  59,
  74,
  934,
  659,
  77,
  324,
  108,
  45,
  125,
  782,
  23,
  293,
  680,
  808,
  2],
 [79,
  3,
  97,
  54,
  12,
  90,
  186,
  431,
  637,
  617,
  19,
  12,
  111,
  9,
  61,
  321,
  145,
  16,
  13],
 [70, 2, 6, 52, 1],
 [14, 576, 463, 3, 2, 474, 613, 1, 1],
 [211, 43, 30, 215, 14, 268, 753, 118, 1],
 [23, 35, 457, 6, 30, 25, 47, 109, 71, 84, 355, 2],
 [210,
  32,
  18,
  62,
  476,
  32,
  87,
  610,
  6,
  19,
  12,
  245,
  660,
  444,
  162,
  457,
  337,
  655,
  245,
  48],
 [173, 3, 314, 1, 60],
 [167, 3, 29, 55, 20, 6, 167],
 [985, 394, 172, 17, 66, 63, 4, 344, 241, 275, 146, 253, 16, 2, 1],
 [55, 3, 93, 412, 53, 56, 774, 6, 301],
 [701, 9, 16, 13, 812, 47, 33, 11, 7, 168, 722, 47, 106],
 [2,
  3,
  394,
  105,
  394,
  17,
  522,
  155,
  134,
  385,
  224,
  47,
  291,
  62,
  15,
  19,
  12,
  17],
 [146,
  538,
  32,
  36,
  861,
  30,
  32,
  861,
  61,
  9,
  160,
  55,
  3,
  133,
  146,
  30,
  11,
  5,
  29,
  20,
  6,
  575,
  747,
  368,
  123],
 [863, 3, 482, 30, 19, 12],
 [142, 328, 4, 867, 294, 294, 1, 2, 271, 48, 3, 1],
 [874, 495, 10, 66, 874, 72, 182, 124, 17, 452, 23, 10, 90, 243],
 [14,
  734,
  977,
  675,
  394,
  248,
  117,
  3,
  684,
  901,
  924,
  14,
  684,
  72,
  117,
  943,
  68],
 [935,
  41,
  13,
  81,
  243,
  70,
  224,
  63,
  35,
  668,
  110,
  524,
  216,
  110,
  6,
  135,
  439,
  884,
  63],
 [485,
  471,
  702,
  8,
  5,
  72,
  22,
  9,
  12,
  184,
  492,
  661,
  205,
  428,
  40,
  198,
  153,
  539,
  271,
  1],
 [2, 95, 65, 122, 358, 35, 1, 60, 83, 6, 65, 2],
 [649, 404, 521, 4, 126, 66, 69, 3, 120, 168, 17, 386],
 [306, 71, 5, 201, 319, 3, 113, 803, 32, 8, 65, 448, 1, 3, 408, 54, 692],
 [151, 638, 32, 557, 7, 164, 477, 201, 754, 99, 3, 50, 1],
 [337,
  529,
  451,
  10,
  649,
  105,
  146,
  267,
  160,
  292,
  832,
  29,
  20,
  6,
  141,
  196,
  22,
  203,
  49,
  917,
  2],
 [109, 446, 191, 50, 669, 154, 46, 149, 214, 3, 50, 210, 139, 393, 1, 1],
 [16, 13, 2, 92, 69, 133, 964, 62, 235, 203, 110, 1],
 [40, 143, 785, 254, 1],
 [23,
  54,
  42,
  28,
  115,
  964,
  107,
  68,
  5,
  515,
  38,
  144,
  64,
  36,
  160,
  353,
  545,
  326,
  104,
  735,
  80,
  15,
  565,
  162,
  545,
  15,
  2],
 [52, 978, 689, 795, 76, 14, 70, 91],
 [22, 343, 164, 161, 54, 5, 89, 71, 1],
 [46,
  31,
  195,
  6,
  300,
  18,
  930,
  17,
  29,
  20,
  39,
  130,
  46,
  31,
  195,
  775,
  116,
  9,
  168,
  17,
  685,
  2],
 [923,
  6,
  5,
  20,
  24,
  435,
  28,
  387,
  510,
  651,
  868,
  28,
  184,
  557,
  493,
  23,
  535,
  48],
 [118,
  156,
  186,
  164,
  27,
  19,
  12,
  245,
  329,
  601,
  420,
  828,
  472,
  701,
  32,
  977,
  168,
  16,
  13,
  2],
 [9, 38, 28, 234, 29, 20, 69, 59, 197, 193, 875],
 [965, 38, 438, 133, 127, 37, 463, 275, 2, 3, 686, 18, 641, 1],
 [818,
  250,
  925,
  98,
  190,
  7,
  39,
  130,
  383,
  3,
  11,
  73,
  72,
  120,
  729,
  9,
  299,
  31,
  55],
 [7,
  26,
  662,
  3,
  22,
  54,
  803,
  12,
  46,
  343,
  827,
  77,
  26,
  230,
  42,
  64,
  28,
  400,
  1],
 [3,
  353,
  9,
  29,
  254,
  294,
  136,
  29,
  20,
  6,
  294,
  629,
  301,
  273,
  294,
  244,
  974,
  332,
  354,
  225,
  338,
  47,
  106],
 [804,
  7,
  130,
  114,
  61,
  516,
  398,
  123,
  82,
  67,
  114,
  117,
  332,
  3,
  62,
  670,
  31,
  182,
  103,
  398,
  123,
  85,
  1],
 [426,
  103,
  398,
  123,
  182,
  67,
  155,
  103,
  123,
  9,
  117,
  332,
  3,
  176,
  129,
  180,
  76,
  161,
  467,
  369,
  117],
 [217, 11, 12, 149, 567, 18, 722, 180, 8, 395, 14, 48, 1],
 [37, 875, 59, 33, 8, 5, 746, 56, 53, 56, 143, 496, 10, 3, 289],
 [8, 12, 686, 178, 19, 185, 12, 282, 29, 690, 16, 13, 2, 697, 776, 913],
 [65, 6, 87, 30, 169, 502, 155, 517, 441, 237, 28, 256, 40, 425, 2, 289],
 [77,
  8,
  5,
  114,
  23,
  293,
  30,
  250,
  85,
  15,
  17,
  46,
  538,
  146,
  644,
  39,
  142,
  3,
  618,
  1],
 [89,
  17,
  36,
  11,
  8,
  5,
  372,
  235,
  131,
  15,
  2,
  69,
  225,
  131,
  47,
  374,
  9,
  10,
  242,
  24,
  231,
  31],
 [539,
  68,
  630,
  329,
  586,
  569,
  104,
  809,
  3,
  67,
  503,
  14,
  134,
  719,
  798,
  876,
  767,
  284,
  809],
 [58, 18, 239, 97, 28, 19, 670, 31, 516, 28, 986, 24, 2, 29, 12, 1],
 [15, 287, 97, 58, 146, 287, 61, 46, 393, 6, 9, 1],
 [99, 86, 96, 3, 50, 400, 1],
 [210, 243, 70, 3, 1],
 [204, 30, 250, 151, 57, 237, 38, 22, 227, 553, 71, 216, 18, 245, 1],
 [7, 127, 27, 57, 754, 3, 21, 109, 553, 78, 281, 964, 1],
 [7, 127, 27, 57, 754, 3, 21, 109, 553, 78, 281, 964, 1],
 [386, 263, 9, 31, 28, 6, 344, 20, 17, 125, 690, 15, 17, 2, 3],
 [15, 3, 744, 783, 159, 882, 1],
 [45,
  333,
  558,
  130,
  265,
  671,
  103,
  398,
  123,
  3,
  21,
  100,
  710,
  103,
  123,
  822,
  134,
  130,
  164,
  398,
  123,
  1],
 [794, 5, 36, 136, 37, 533, 656, 3, 76, 166, 368, 88, 726, 180, 54, 26],
 [23, 183, 144, 64, 7, 18, 15, 189, 706, 128, 67, 380, 3, 1],
 [18,
  32,
  183,
  4,
  208,
  10,
  354,
  447,
  18,
  89,
  685,
  693,
  212,
  165,
  768,
  220,
  49,
  729,
  107,
  3,
  813,
  289,
  1],
 [805,
  499,
  167,
  62,
  2,
  524,
  499,
  580,
  446,
  524,
  132,
  72,
  753,
  167,
  624,
  499,
  158,
  273],
 [14, 339, 315, 112, 40, 570, 117, 332, 3, 711, 339, 114, 23, 33, 1],
 [707, 501, 83, 171, 141, 4, 166, 241, 330, 89, 707, 76, 48],
 [337, 8, 5, 373, 537, 304, 263, 49, 5, 812, 100, 540, 55, 16, 13, 2, 1],
 [805, 321, 145, 151, 218, 689, 671, 358, 2, 407, 20, 1],
 [32, 470, 7, 145, 40, 36, 442, 32, 3, 449, 549, 113, 115, 261, 698],
 [580,
  376,
  563,
  178,
  110,
  263,
  723,
  545,
  372,
  19,
  12,
  672,
  654,
  118,
  314,
  329,
  82,
  392,
  118,
  2],
 [506,
  9,
  334,
  54,
  5,
  506,
  657,
  506,
  30,
  525,
  69,
  210,
  66,
  12,
  19,
  12,
  194,
  33,
  2,
  54],
 [2, 221, 86, 422, 441, 136, 221, 339, 554, 83, 258, 486, 118, 14, 104, 1],
 [433, 307, 138, 124, 253, 410, 87, 144, 7, 64, 48],
 [400, 912, 16, 13, 29, 565, 6, 53, 56, 376, 837, 89, 356],
 [17, 27, 754, 271, 1],
 [118,
  675,
  81,
  583,
  110,
  27,
  28,
  52,
  223,
  62,
  127,
  246,
  10,
  86,
  559,
  523,
  6,
  846],
 [148, 405, 41, 2, 346, 40, 61, 5, 722, 350, 413, 19, 12, 62, 92, 110, 172, 1],
 [32,
  12,
  703,
  726,
  200,
  6,
  375,
  10,
  3,
  69,
  346,
  924,
  745,
  10,
  65,
  134,
  404,
  262,
  814],
 [712,
  735,
  470,
  58,
  85,
  11,
  2,
  171,
  601,
  264,
  91,
  17,
  110,
  933,
  506,
  12,
  19,
  1],
 [100,
  400,
  3,
  69,
  46,
  45,
  822,
  173,
  195,
  234,
  5,
  397,
  354,
  355,
  9,
  292,
  88,
  471],
 [641, 647, 282, 2, 17, 118, 19, 1],
 [14,
  315,
  613,
  2,
  407,
  559,
  221,
  577,
  564,
  339,
  507,
  441,
  577,
  257,
  752,
  469,
  577,
  49,
  869,
  420,
  112,
  17,
  1],
 [20,
  690,
  138,
  847,
  267,
  9,
  141,
  6,
  39,
  17,
  180,
  399,
  566,
  105,
  2,
  29,
  232,
  1,
  60],
 [118,
  71,
  27,
  388,
  69,
  16,
  13,
  526,
  27,
  426,
  174,
  118,
  9,
  49,
  902,
  258,
  54,
  5],
 [210, 32, 124, 766, 51, 2, 500, 1],
 [18, 424, 687, 163, 76, 17, 257, 175, 161, 467, 92, 38, 8, 5, 3, 2],
 [97, 62, 401, 166, 29, 28, 300, 6, 39, 842, 73, 534, 385, 713, 271, 48],
 [229,
  307,
  15,
  18,
  6,
  41,
  29,
  20,
  41,
  39,
  273,
  183,
  3,
  87,
  218,
  103,
  587,
  433,
  15,
  729],
 [545, 19, 12, 663, 67, 149, 2],
 [120,
  36,
  140,
  86,
  96,
  23,
  54,
  231,
  31,
  327,
  107,
  5,
  963,
  163,
  445,
  11,
  511,
  3],
 [916,
  734,
  3,
  326,
  165,
  19,
  12,
  457,
  222,
  890,
  31,
  489,
  31,
  465,
  49,
  161,
  979,
  31,
  465,
  147,
  9,
  23,
  242,
  24,
  382],
 [377, 571, 129, 11, 140, 36, 28, 344, 6, 581, 11, 15, 2, 3],
 [6,
  135,
  71,
  231,
  31,
  869,
  189,
  126,
  77,
  289,
  230,
  162,
  488,
  569,
  458,
  231,
  31,
  555,
  192,
  374,
  652,
  412,
  171,
  2,
  3],
 [821, 16, 13, 3, 2, 16, 813, 233, 500, 1],
 [125, 12, 30, 80, 168, 741, 30, 287, 1],
 [68, 474, 287, 9, 5, 292, 42, 6, 891, 28, 52, 417, 491, 46, 746, 405, 2],
 [512, 365, 242, 24, 588, 7, 783, 3],
 [72, 237, 78, 145, 84, 162, 7, 54, 85, 37, 162, 398, 966, 2, 48, 487],
 [187,
  122,
  187,
  15,
  598,
  104,
  67,
  30,
  134,
  211,
  261,
  374,
  460,
  534,
  508,
  591,
  823,
  247,
  2],
 [46, 132, 198, 3, 10, 19, 5, 14, 1, 1],
 [7, 435, 13],
 [456,
  780,
  63,
  26,
  19,
  12,
  497,
  22,
  502,
  448,
  65,
  689,
  26,
  644,
  22,
  91,
  405,
  2],
 [77, 37, 162, 1],
 [89,
  9,
  28,
  365,
  24,
  53,
  205,
  123,
  64,
  144,
  903,
  25,
  66,
  69,
  2,
  9,
  17,
  307,
  242,
  24,
  500,
  1],
 [283, 429, 28, 6, 53, 205, 28, 190, 198, 2, 1],
 [311, 943, 19, 12, 72, 892, 723, 12, 443, 166, 179, 448, 311, 2, 271, 3],
 [30,
  411,
  16,
  13,
  29,
  847,
  119,
  884,
  710,
  149,
  766,
  6,
  178,
  478,
  250,
  356,
  190,
  385,
  567],
 [3, 54, 71, 5, 9, 292, 127, 995, 942, 252, 785, 307, 384, 71, 178, 560],
 [10, 431, 183, 82, 325, 3, 21, 61, 5, 71, 82, 173, 423, 19, 12, 1, 408, 2, 1],
 [7,
  128,
  714,
  267,
  23,
  178,
  40,
  26,
  156,
  843,
  957,
  661,
  155,
  567,
  3,
  232,
  25,
  424,
  1],
 [270, 394, 96, 3, 189, 259, 256, 19, 12, 10, 470, 10, 394],
 [127, 11, 8, 5, 912, 178, 250, 53, 56, 46, 350, 566, 305, 2, 1],
 [229,
  38,
  985,
  253,
  394,
  118,
  139,
  316,
  138,
  75,
  54,
  5,
  41,
  3,
  433,
  328,
  198,
  188,
  139,
  1],
 [151, 795, 6, 95, 85, 119, 28, 155, 2],
 [29, 412, 122, 123, 64, 144, 122, 108, 2, 208, 19, 8, 12, 610, 83, 32, 1],
 [31,
  29,
  20,
  10,
  189,
  10,
  203,
  149,
  89,
  31,
  489,
  77,
  128,
  98,
  19,
  12,
  502,
  134,
  155,
  670,
  31,
  3,
  411,
  203,
  924,
  6],
 [806, 967, 11, 282, 3, 742, 3, 38, 744, 17, 29, 20, 374, 385, 766, 53, 56, 6],
 [820,
  5,
  59,
  6,
  11,
  17,
  53,
  56,
  512,
  15,
  436,
  522,
  205,
  15,
  363,
  695,
  153,
  77,
  699,
  326,
  718,
  62,
  476,
  445,
  188,
  3,
  29,
  20],
 [1,
  264,
  172,
  18,
  866,
  91,
  10,
  14,
  315,
  975,
  677,
  290,
  110,
  264,
  172,
  70,
  3,
  46,
  622,
  623],
 [23, 7, 5, 105, 48],
 [173, 3, 314, 1],
 [18,
  254,
  39,
  6,
  649,
  29,
  20,
  598,
  152,
  502,
  65,
  517,
  231,
  31,
  959,
  385,
  235,
  138,
  25,
  433,
  299,
  2],
 [446, 829, 452, 633, 70, 3, 214, 393, 1, 60, 88],
 [284, 128, 33, 42, 39, 130, 141, 837, 290, 416, 85, 18, 355, 23, 1],
 [106, 23, 99, 2, 1, 60],
 [414, 28, 6, 3, 208, 252, 20, 237, 533, 698, 652, 1],
 [5, 30, 726, 52, 227, 5, 265, 912, 54, 2, 1],
 [257, 2, 14, 1, 3, 2, 2, 421],
 [204, 8, 5, 12, 381, 912, 59, 171, 25, 58, 5, 62, 28, 3, 2],
 [174, 17, 455, 7, 80, 20, 67, 363, 127, 163, 36, 32, 48],
 [28, 52, 830, 44, 4, 495, 830, 88, 830, 2, 48, 837, 40],
 [],
 [91, 204, 3, 1, 91, 59, 182, 204, 560, 54, 5, 980, 214, 148, 69, 3, 1],
 [7, 94, 7, 37, 748, 179, 118, 13],
 [29, 20, 77, 422, 55, 263, 292, 15, 20, 6, 344, 16, 2, 1],
 [248, 28, 6, 185, 364, 560, 231, 31, 111, 2, 1],
 [160,
  30,
  8,
  5,
  968,
  185,
  155,
  72,
  225,
  547,
  29,
  20,
  26,
  80,
  27,
  769,
  902,
  78,
  109,
  5,
  67,
  754,
  329,
  345,
  977,
  48,
  2],
 [24, 18, 726, 69, 2, 3, 366, 253, 586, 926, 10, 47, 71, 5, 1],
 [603,
  147,
  16,
  13,
  495,
  6,
  559,
  63,
  10,
  251,
  35,
  55,
  6,
  273,
  381,
  981,
  10,
  427,
  381,
  11],
 [9, 37, 3, 739, 15, 949, 6, 788, 722, 28, 294, 294, 294, 294],
 [42, 377, 636, 465, 336, 836, 969, 634, 33, 11, 8, 5, 48],
 [294,
  378,
  874,
  546,
  182,
  339,
  452,
  172,
  216,
  454,
  198,
  10,
  114,
  70,
  3,
  855,
  1,
  960,
  1,
  1],
 [652, 652, 119, 8, 5, 85, 331, 48],
 [29, 269, 269, 785, 596, 416, 85, 389, 6, 10, 39, 423, 272, 2, 1],
 [54,
  5,
  71,
  239,
  197,
  42,
  76,
  107,
  106,
  3,
  50,
  148,
  660,
  87,
  176,
  19,
  194,
  624,
  941,
  201,
  1],
 [438, 172, 223, 36, 39, 168, 19, 556, 39, 19, 12, 244, 101, 17, 27, 60, 19],
 [869, 129, 68, 98, 25, 700, 128, 783, 28, 6, 10, 39, 37, 434, 146, 2],
 [28,
  99,
  3,
  79,
  499,
  18,
  279,
  170,
  4,
  811,
  338,
  95,
  618,
  977,
  10,
  618,
  10,
  618,
  336,
  54,
  10,
  14,
  618,
  10,
  3,
  1],
 [212, 25, 11, 376, 444, 98, 55, 475, 47, 712, 16, 13, 1],
 [29,
  20,
  59,
  217,
  73,
  409,
  14,
  434,
  9,
  69,
  833,
  133,
  3,
  10,
  3,
  29,
  20,
  233,
  1],
 [150, 69, 3, 806, 361, 29, 8, 5, 331, 140, 195, 39, 1],
 [146, 29, 18, 6, 904, 789, 36, 216, 3, 2, 1, 1],
 [301, 204, 762, 3, 54, 5, 3, 2, 1],
 [30,
  250,
  768,
  242,
  24,
  47,
  295,
  9,
  349,
  10,
  180,
  84,
  578,
  197,
  215,
  10,
  84,
  3,
  1],
 [139,
  65,
  83,
  555,
  754,
  87,
  19,
  294,
  294,
  294,
  294,
  294,
  294,
  7,
  164,
  477,
  201,
  281,
  964,
  99,
  3,
  50,
  1],
 [185, 22, 11, 8, 5, 268, 6, 877, 6, 733, 158, 2, 3, 1],
 [41, 2, 18, 28, 41, 2, 18, 28, 6, 2, 412, 1, 1],
 [18, 214, 3, 942, 14, 387, 330, 211, 136, 164],
 [41,
  2,
  29,
  20,
  11,
  45,
  479,
  640,
  20,
  180,
  20,
  652,
  416,
  189,
  6,
  156,
  20,
  53,
  205,
  416,
  42,
  37,
  697],
 [2, 552, 336, 243, 499, 847, 172, 127, 15, 671, 3, 1, 54, 101, 5, 528],
 [805, 405, 5, 83, 99, 2, 269, 1, 60, 54, 21, 3],
 [54, 5, 528, 25, 80],
 [28,
  291,
  181,
  121,
  357,
  205,
  53,
  291,
  6,
  20,
  11,
  291,
  299,
  11,
  6,
  15,
  398,
  386,
  247,
  22,
  664,
  2,
  471,
  432,
  12],
 [541, 661, 496, 5, 1, 60, 905, 195, 2, 541, 29],
 [158, 16, 13, 581, 86, 96, 257, 341, 416, 31, 353, 12, 815, 256, 1],
 [490, 5, 77, 54, 26, 231, 31, 842, 282, 94, 2, 1],
 [169, 458, 159, 8, 5, 582, 556, 570, 72, 730, 103, 131, 3],
 [156,
  173,
  248,
  30,
  264,
  88,
  12,
  214,
  3,
  198,
  623,
  319,
  1,
  3,
  12,
  408,
  54,
  156,
  1],
 [111,
  69,
  806,
  29,
  370,
  9,
  20,
  64,
  183,
  447,
  571,
  176,
  73,
  533,
  6,
  39,
  188,
  5,
  15,
  565,
  48],
 [75, 17, 23, 6, 65, 517, 32, 11, 159, 35, 366, 166, 790, 2, 260],
 [522, 848, 370, 514, 570, 3, 111, 514, 370, 7, 406, 923, 570, 5, 686, 161],
 [359, 74, 5, 111, 844, 2, 812, 88, 1],
 [40, 390, 267, 169, 870, 71, 16, 13, 61, 31, 30, 6, 405, 8, 5, 15, 45, 28],
 [368, 6, 15, 240, 87, 60, 902, 10, 960],
 [420,
  77,
  146,
  281,
  12,
  197,
  550,
  193,
  765,
  3,
  975,
  281,
  361,
  37,
  463,
  19,
  65,
  121,
  78,
  17,
  1],
 [605,
  317,
  770,
  593,
  160,
  55,
  146,
  22,
  225,
  19,
  12,
  160,
  554,
  28,
  9,
  17,
  55,
  601,
  25,
  709,
  9,
  113,
  107],
 [871, 80, 124, 34, 53, 56, 72, 17, 15, 287, 500, 2],
 [25, 987, 3, 50, 120, 122, 75, 282, 431, 169, 1],
 [119, 43, 159, 4, 182, 271, 48],
 [53, 56, 57, 8, 5, 478, 98, 287, 50, 781, 51, 2, 1],
 [2, 11, 12, 233, 329, 244, 151, 237, 186, 19, 256, 94, 736],
 [18,
  100,
  111,
  110,
  8,
  5,
  215,
  450,
  76,
  22,
  72,
  55,
  386,
  906,
  108,
  87,
  85,
  31,
  517,
  32,
  186,
  557,
  48,
  3,
  16,
  13],
 [69, 3, 123, 61, 378, 14, 282, 161, 52, 173, 892, 257, 176, 161, 1],
 [23, 103, 270, 62, 127, 11, 23, 356, 40, 98, 6, 28, 3, 123, 179],
 [46, 132],
 [376,
  10,
  600,
  38,
  8,
  5,
  936,
  673,
  178,
  566,
  494,
  799,
  22,
  796,
  10,
  803,
  893,
  2],
 [153, 512, 140, 353, 19, 6, 12, 368, 28, 515, 652, 651, 363, 11, 299, 472, 2],
 [100,
  132,
  353,
  8,
  5,
  141,
  2,
  18,
  561,
  530,
  358,
  35,
  5,
  39,
  130,
  62,
  665,
  60,
  1],
 [759, 400, 25, 306, 61, 405, 388, 69, 2, 191, 32, 456, 225, 201, 54, 1],
 [10, 14, 378, 486, 399, 75, 139, 884, 856, 142, 81, 528, 1, 2, 3, 1],
 [15, 33, 7, 29, 20, 287, 285, 683, 23, 201, 48, 16, 13],
 [228, 25, 173, 216, 6, 904, 54, 84, 3, 21, 1],
 [46,
  27,
  25,
  28,
  6,
  637,
  50,
  16,
  13,
  179,
  684,
  900,
  209,
  595,
  27,
  25,
  455,
  264,
  92,
  28,
  6],
 [11,
  23,
  907,
  92,
  131,

In [157]:
X_train = pad_sequences(sequences, maxlen=50, padding='post')

In [159]:
X_train[0].shape

(50,)

In [161]:
vocab_size = len(word_index)+1
embedding_dim = 16
max_len = 10

In [163]:
vocab_size

81628

In [175]:
model = Sequential()
model.add(Input(shape = X_train[0].shape))
model.add(Embedding(input_dim = 1000,output_dim=embedding_dim))
model.add(GlobalAveragePooling1D())
model.add(Dense(32,activation="relu"))
model.add(Dense(16,activation="relu"))
model.add(Dense(5,activation="softmax"))

In [177]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 50, 16)         │     1,306,048 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling1d_2      │ (None, 16)             │             0 │
│ (GlobalAveragePooling1D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 32)             │           544 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 5)              │            85 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,307,205 (4.99 MB)

 Trainable params: 1,307,205 (4.99 MB)

 Non-trainable params: 0 (0.00 B)

In [173]:
16000/17157

0.9325639680596841

In [169]:
model.compile(optimizer="sgd",loss="categorical_crossentropy",metrics=["accuracy"])

In [171]:
model.fit(X_train,y_train,epochs=20,verbose=1)

Epoch 1/20
1287/1287 ━━━━━━━━━━━━━━━━━━━━ 1s 275us/step - accuracy: 0.2725 - loss: 1.5882
Epoch 2/20
1287/1287 ━━━━━━━━━━━━━━━━━━━━ 0s 265us/step - accuracy: 0.2727 - loss: 1.5763
Epoch 3/20
1287/1287 ━━━━━━━━━━━━━━━━━━━━ 0s 266us/step - accuracy: 0.2775 - loss: 1.5701
Epoch 4/20
1287/1287 ━━━━━━━━━━━━━━━━━━━━ 0s 262us/step - accuracy: 0.2774 - loss: 1.5694
Epoch 5/20
1287/1287 ━━━━━━━━━━━━━━━━━━━━ 0s 261us/step - accuracy: 0.2754 - loss: 1.5681
Epoch 6/20
1287/1287 ━━━━━━━━━━━━━━━━━━━━ 0s 265us/step - accuracy: 0.2753 - loss: 1.5604
Epoch 7/20
1287/1287 ━━━━━━━━━━━━━━━━━━━━ 0s 263us/step - accuracy: 0.2805 - loss: 1.5542
Epoch 8/20
1287/1287 ━━━━━━━━━━━━━━━━━━━━ 0s 261us/step - accuracy: 0.2983 - loss: 1.5434
Epoch 9/20
1287/1287 ━━━━━━━━━━━━━━━━━━━━ 0s 265us/step - accuracy: 0.3065 - loss: 1.5316
Epoch 10/20
1287/1287 ━━━━━━━━━━━━━━━━━━━━ 0s 267us/step - accuracy: 0.3079 - loss: 1.5243
Epoch 11/20
1287/1287 ━━━━━━━━━━━━━━━━━━━━ 0s 269us/step - accuracy: 0.3066 - loss: 1.5213
Epoch 12/20
1287/1287 ━━━━━━━━━━━━━━━━━━━━ 0s 265us/step - accuracy: 0.3052 - loss: 1.5215
Epoch 13/20
1287/1287 ━━━━━━━━━━━━━━━━━━━━ 0s 264us/step - accuracy: 0.3043 - loss: 1.5212
Epoch 14/20
1287/1287 ━━━━━━━━━━━━━━━━━━━━ 0s 304us/step - accuracy: 0.3051 - loss: 1.5212
Epoch 15/20
1287/1287 ━━━━━━━━━━━━━━━━━━━━ 0s 276us/step - accuracy: 0.3042 - loss: 1.5223
Epoch 16/20
1287/1287 ━━━━━━━━━━━━━━━━━━━━ 0s 327us/step - accuracy: 0.3040 - loss: 1.5211
Epoch 17/20
1287/1287 ━━━━━━━━━━━━━━━━━━━━ 0s 272us/step - accuracy: 0.3055 - loss: 1.5187
Epoch 18/20
1287/1287 ━━━━━━━━━━━━━━━━━━━━ 0s 266us/step - accuracy: 0.3075 - loss: 1.5173
Epoch 19/20
1287/1287 ━━━━━━━━━━━━━━━━━━━━ 0s 264us/step - accuracy: 0.3104 - loss: 1.5170
Epoch 20/20
1287/1287 ━━━━━━━━━━━━━━━━━━━━ 0s 265us/step - accuracy: 0.3055 - loss: 1.5168

In [179]:
df_test = pd.read_csv("./data/Covid/Corona_NLP_test.csv")

In [181]:
df_test.head()

,UserName,ScreenName,Location,TweetAt,OriginalTweet,Sentiment
0,1,44953,NYC,02-03-2020,TRENDING: New Yorkers encounter empty supermar...,Extremely Negative
1,2,44954,"Seattle, WA",02-03-2020,When I couldn't find hand sanitizer at Fred Me...,Positive
2,3,44955,NaN,02-03-2020,Find out how you can protect yourself and love...,Extremely Positive
3,4,44956,Chicagoland,02-03-2020,#Panic buying hits #NewYork City as anxious sh...,Negative
4,5,44957,"Melbourne, Victoria",03-03-2020,#toiletpaper #dunnypaper #coronavirus #coronav...,Neutral

In [191]:
text = df_test["OriginalTweet"][0]

In [193]:
text

'TRENDING: New Yorkers encounter empty supermarket shelves (pictured, Wegmans in Brooklyn), sold-out online grocers (FoodKick, MaxDelivery) as #coronavirus-fearing shoppers stock up https://t.co/Gr76pcrLWh https://t.co/ivMKMsqdT1'

In [195]:
cleaned_text = clean_text(text)

In [197]:
cleaned_text

'trending  new yorkers encounter empty supermarket shelve  picture  wegmans brooklyn   soldout online grocers  foodkick  maxdelivery   coronavirusfearing shoppers stock https  tcogr76pcrlwh https  tcoivmkmsqdt1'

In [203]:
test_sequences = tokenizer.texts_to_sequences([cleaned_text])

In [205]:
test_sequences

[[45, 144, 7, 64, 875, 19, 281, 28, 1, 1]]

In [207]:
padded_test_seq = pad_sequences(test_sequences, maxlen=50, padding='post')

In [209]:
padded_test_seq

array([[ 45, 144,   7,  64, 875,  19, 281,  28,   1,   1,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]],
      dtype=int32)

In [213]:
y_pred = model.predict(padded_test_seq)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step

In [217]:
y_pred.sum()

1.0

In [221]:
y_pred

array([[0.20240812, 0.20137554, 0.2010356 , 0.1961286 , 0.19905207]],
      dtype=float32)

In [219]:
np.argmax(y_pred)

0

In [229]:
le.inverse_transform([0])

array(['Extremely Negative'], dtype=object)